Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Models/Adres.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AntonVlasiukLab5Home.Models
{
    public class Adres : ModelBase
    {
        public string City { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Models/Hobby.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AntonVlasiukLab5Home.Models
{
    public class Hobby : ModelBase
    {
        /// <summary>
        /// name of Hobby
        /// </summary>
        public string Name { get; set; }
        public List<Prize> Prizes { get; set; }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Models/ModelBase.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AntonVlasiukLab5Home.Models
{
    public abstract class ModelBase
    {
        [Key]
        public int Id { get; set; }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Models/Prize.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AntonVlasiukLab5Home.Models
{
    /// <summary>
    /// earned reward 
    /// </summary>
    public class Prize : ModelBase 
    {
        /// <summary>
        /// Signature of person, who gave this prize
        /// </summary>
        public string Signature { get; set; }

        /// <summary>
        /// where it was
        /// </summary>
        public Adres Where { get; set; }

        /// <summary>
        /// Cheerful comment for motivation
        /// </summary>
        public string Comment { get; set; }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Models/SchoolClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AntonVlasiukLab5Home.Models
{
    public class SchoolClass : ModelBase
    {
        public string ClassName { get; set; }
        public List<Student> Students { get; set; }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Models/SchoolContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace AntonVlasiukLab5Home.Models
{
    public class SchoolContext : DbContext
    {
        public IDbSet<SchoolClass> SchoolClasses { get; set; }
        public IDbSet<Student> Students { get; set; }
        public IDbSet<Adres> Adreses { get; set;}

        public SchoolContext() : base("MyNewSchool"){ }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AntonVlasiukLab5Home.Models
{
    public class Student : ModelBase      
    {
        [Required(ErrorMessage = "Name is required")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is also required")]
        public string LastName { get; set; }

        [Range(1, 122, ErrorMessage = "Your age must be between 1 and 122 Why 122? Check who is Jeanne Calment from French")]
        public int Age { get; set; }

        public Adres Adres { get; set; }

        public List<Hobby> Hobby { get; set; }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Controllers/AdresController.cs
using AntonVlasiukLab5Home.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AntonVlasiukLab5Home.Controllers
{
    public class AdresController : Controller
    {
        // GET: Adres
        public ActionResult Index()
        {
            List<Adres> adreses;

            using (var ctx = new SchoolContext())
            {
                adreses = ctx.Adreses.ToList();
            }

            return View(adreses);
        }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Controllers/FirstPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AntonVlasiukLab5Home.Controllers
{
    public class FirstPageController : Controller
    {
        // GET: FirstPage
        public ActionResult Index()
        {
            return View();
        }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Controllers/StudentController.cs
using AntonVlasiukLab5Home.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AntonVlasiukLab5Home.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            List<Student> students;

            using (var ctx = new SchoolContext())
            {
                students = ctx.Students.ToList();
            }

            return View(students);
        }

        public ActionResult Add()
        {
            return View(new Student());
        }

        [HttpPost]
        public ActionResult Add(Student post)
        {
            if (!ModelState.IsValid)
            {
                return View(post);
            }

            using (var ctx = new SchoolContext())
            {
                ctx.Students.Add(post);
                ctx.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (var ctx = new SchoolContext())
            {
                var dbEntry = ctx.Students.SingleOrDefault(m => m.Id == id);
                ctx.Students.Remove(dbEntry);
                ctx.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            Student student;

            using (var ctx = new SchoolContext())
            {
                student = ctx.Students.SingleOrDefault(m => m.Id == id);
            }

            return View(student);
        }

        [HttpPost]
        public ActionResult Edit(int id, Student student)
        {
            if (!ModelState.IsValid)
            {
                return View(student);
            }

            using (var ctx = new SchoolContext())
            {
                var dbEntry = ctx.Students.SingleOrDefault(p => p.Id == id);
                dbEntry.FirstName = student.FirstName;
                dbEntry.LastName = student.LastName;
                dbEntry.Age = student.Age;
                ctx.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Views/Adres/Index.cshtml
@model List<AntonVlasiukLab5Home.Models.Adres>

@{
    ViewBag.Title = "Adreses";
}

<h2>Adreses</h2>

@foreach (var adres in Model)
{
    <span>City: </span>
    @adres.City; <br />
    <span>Street: </span>
    @adres.Street; <br />
    <span>House: </span>
    @adres.House; <br />
    <br />
}

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Views/FirstPage/Index.cshtml
@{
    ViewBag.Title = "First page";
}

<h1>Hi!</h1>
<h2>You are on first page of my super site!</h2>
<h3>I have navigation buttons. Look above.</h3>
<h3>I made rendering only for 2 table, because it's really same. Hope, it`s fine...</h3>

Zad1/AntonVlasiukLab6Home/AntonVlasiukLab5Home/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Adreses", "Index", "Adres", new { area = "" }, new { @class = "navbar-brand" })

                @Html.ActionLink("Students", "Index", "Student", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>